---
title: "car_accidents"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
library(dbplyr)
library(data.table)
```


```{r}
accidents<-fread('small_accidents.csv',data.table=FALSE)
```



```{r}
accidents %>% 
  count(State) %>% 
  arrange(desc(n)) %>% 
  head(12)
```

```{r}
accidents %>%
  summarise_all(~ mean(is.na(.))) %>% 
  pivot_longer(1:46, names_to = "Variables to drop", values_to = "NA proportion") %>% 
  filter(`NA proportion` >= 0.5)

```

```{r}
accidents %>% 
  mutate(TMC = as.factor(TMC)) %>% 
  count(TMC) %>% 
  ggplot(aes(x = n, y = TMC)) +
  geom_col()
```


```{r}
accidents_clean <- accidents %>% 
  select(-Source, -End_Lat, -End_Lng, -Number, -ID, -TMC, -Weather_Timestamp, -Airport_Code,-Timezone) 
```

```{r}
accidents_clean %>% 
  mutate(Severity = as.factor(Severity)) %>% 
  count(Severity) %>% 
  ggplot(aes(x = n, y = Severity)) +
  geom_col()
```


```{r}
accidents_clean %>% 
  select(where(is.numeric)) %>% 
  pivot_longer(cols = everything(),
               names_to = "variable", 
               values_to = "value")%>% 
  ggplot(aes(x = value)) +
  geom_histogram() +
  facet_wrap(vars(variable), 
             scales = "free")
```


>This variable is not very informative and it has many NA values


```{r}
accidents %>%
  count(Start_Time) 

```
>We could group the time by hours. 


```{r}
accidents %>%
  count(County) %>%
  arrange(desc(n)) %>% 
  top_n(10, n) %>% 
  ggplot(aes(y = County, x = n)) +
  geom_col()
  
```

```{r}
cars_clean %>%
  count(State) %>%
  arrange(desc(n)) %>% 
  top_n(10, n) %>% 
  ggplot(aes(y = State, x = n)) +
  geom_col()
  
```


```{r}
accidents %>%
  filter(State == "CA") %>% 
  count(County) %>%
  ggplot(aes(y = County, x = n)) +
  geom_col()
```


```{r}
accidents %>%
  filter(State == "IL") %>% 
  count(County) %>%
  ggplot(aes(y = County, x = n)) +
  geom_col()
```

```{r}
accidents %>%
  filter(State == "FL") %>% 
  count(County) %>%
  ggplot(aes(y = County, x = n)) +
  geom_col()
```

```{r}
accidents %>%
  filter(State == "NC") %>% 
  count(County) %>%
  ggplot(aes(y = County, x = n)) +
  geom_col()
```


```{r}
accidents %>%
  filter(State == "NY") %>% 
  count(County) %>%
  ggplot(aes(y = County, x = n)) +
  geom_col()
```

>We could draw comparisons between counties with most observations, or simply stick with the 10 biggest state categories. 


```{r}
accidents %>%
  ggplot(aes(`Temperature(F)`, ..prop.., group = Severity)) +
  geom_bar(aes(fill = Severity), position = "dodge") 
```

>It is skewed to the left, it seems like heat could be associated with accidents, also it differs for the different types of Severyty. 

```{r}
accidents %>%
  ggplot(aes(`Wind_Chill(F)`, ..prop.., group = Severity)) +
  geom_bar(aes(fill = Severity), position = "dodge") 
```

